#!/usr/bin/env bash
# Wire the claude-dev containers to start automatically at Windows logon.
#
# What it does: drops a hidden launcher into your Windows *Startup* folder. At every logon
# Windows runs it, which boots the WSL distro, waits for Docker, and runs host-autostart.sh
# (which starts every claude-* container). No admin rights, no scheduled-task plumbing, no
# console window — and you remove it just by deleting the file (or running --uninstall).
#
# Run this ONCE, from inside WSL, from your real repo checkout:
#   scripts/install-autostart.sh              # install / re-install (idempotent)
#   scripts/install-autostart.sh --status     # show whether it's installed
#   scripts/install-autostart.sh --uninstall  # remove it
#   scripts/install-autostart.sh --cmd         # use a .cmd launcher (brief console flash)
#                                              #   for machines where policy blocks WScript
#   scripts/install-autostart.sh --print       # show what would be written, change nothing
set -uo pipefail

# Repo the launcher points at. Defaults to this script's checkout; override with
# CLAUDE_DEV_REPO_ROOT to target a stable checkout when running from a throwaway worktree.
REPO_ROOT="${CLAUDE_DEV_REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
AUTOSTART_SCRIPT="$REPO_ROOT/scripts/host-autostart.sh"
LOG_DIR="$HOME/.local/state/claude-dev"
LOG_FILE="$LOG_DIR/autostart.log"
LAUNCHER_STEM="claude-dev-autostart"       # file dropped in Startup (.vbs or .cmd)

MODE="install"
USE_CMD=0
for a in "$@"; do
  case "$a" in
    --uninstall) MODE="uninstall" ;;
    --status)    MODE="status" ;;
    --print)     MODE="print" ;;
    --cmd)       USE_CMD=1 ;;
    -h|--help)   sed -n '2,15{s/^# \{0,1\}//;p}' "$0"; exit 0 ;;
    *) echo "unknown arg: $a (try --help)" >&2; exit 2 ;;
  esac
done

die() { echo "install-autostart: $*" >&2; exit 1; }

# --- locate the Windows tools (PATH first, then the standard System32 location) ------------
find_win_tool() {
  local name="$1"
  if command -v "$name" >/dev/null 2>&1; then command -v "$name"; return 0; fi
  local sys32="/mnt/c/Windows/System32/$name"
  [ -x "$sys32" ] && { echo "$sys32"; return 0; }
  return 1
}
CMD_EXE="$(find_win_tool cmd.exe)" || die "cmd.exe not found — is this a WSL shell with Windows interop enabled?"
command -v wslpath >/dev/null 2>&1 || die "wslpath not found — run this from inside WSL."

# --- resolve the WSL distro name -----------------------------------------------------------
DISTRO="${WSL_DISTRO_NAME:-}"
if [ -f "$REPO_ROOT/config/local.env" ]; then
  cfg_distro="$(sed -n 's/^[[:space:]]*WSL_DISTRO[[:space:]]*=[[:space:]]*//p' "$REPO_ROOT/config/local.env" | tail -1 | tr -d '"'"'"' \r')"
  [ -n "$cfg_distro" ] && DISTRO="$cfg_distro"
fi
DISTRO="${DISTRO:-Ubuntu}"
WSL_USER="$(id -un)"
# wsl.exe's own arg parser does NOT strip quotes from the -d value, so the launchers pass the
# distro name unquoted. A distro name with spaces would break that (and is vanishingly rare).
case "$DISTRO" in *[[:space:]]*)
  echo "install-autostart: WARNING: distro name '$DISTRO' contains spaces; wsl.exe -d may not match it." >&2 ;;
esac

# --- resolve the Windows Startup folder ----------------------------------------------------
APPDATA_WIN="$("$CMD_EXE" /c "echo %APPDATA%" 2>/dev/null | tr -d '\r')"
case "$APPDATA_WIN" in
  ""|"%APPDATA%") die "could not read %APPDATA% via cmd.exe — Windows interop may be disabled." ;;
esac
STARTUP_DIR="$(wslpath -u "$APPDATA_WIN")/Microsoft/Windows/Start Menu/Programs/Startup"
# Allow overriding the target for testing without touching the real Startup folder.
STARTUP_DIR="${CLAUDE_DEV_STARTUP_DIR:-$STARTUP_DIR}"

VBS_PATH="$STARTUP_DIR/$LAUNCHER_STEM.vbs"
CMD_PATH="$STARTUP_DIR/$LAUNCHER_STEM.cmd"

# The bash command the launcher runs inside WSL (single string; paths here have no spaces).
INNER_CMD="mkdir -p '$LOG_DIR' && '$AUTOSTART_SCRIPT' >> '$LOG_FILE' 2>&1"

# Build the launcher body. VBS runs fully hidden; .cmd flashes a console briefly.
vbs_body() {
  # Inside a VBS string literal every " is doubled. The bash -lc argument is wrapped in one
  # pair of (doubled) double-quotes; it contains no double-quotes of its own.
  cat <<EOF
' claude-dev-environment — start dev containers at Windows logon (hidden, no console).
' Generated by scripts/install-autostart.sh. Delete this file (or run --uninstall) to disable.
Set sh = CreateObject("WScript.Shell")
sh.Run "wsl.exe -d $DISTRO -u $WSL_USER -e bash -lc ""$INNER_CMD""", 0, False
EOF
}
cmd_body() {
  cat <<EOF
@echo off
REM claude-dev-environment — start dev containers at Windows logon.
REM Generated by scripts/install-autostart.sh. Delete this file (or run --uninstall) to disable.
wsl.exe -d $DISTRO -u $WSL_USER -e bash -lc "$INNER_CMD"
EOF
}

show_resolved() {
  echo "  repo        : $REPO_ROOT"
  echo "  distro/user : $DISTRO / $WSL_USER"
  echo "  runs        : $AUTOSTART_SCRIPT"
  echo "  log         : $LOG_FILE"
  echo "  startup dir : $STARTUP_DIR"
  echo "  launcher    : $LAUNCHER_STEM.$([ "$USE_CMD" = 1 ] && echo cmd || echo vbs)"
}

case "$MODE" in
  print)
    echo "Would install this logon launcher:"; show_resolved; echo
    echo "----- launcher contents -----"
    if [ "$USE_CMD" = 1 ]; then cmd_body; else vbs_body; fi
    exit 0 ;;

  status)
    echo "Logon auto-start status:"
    found=0
    for p in "$VBS_PATH" "$CMD_PATH"; do
      [ -f "$p" ] && { echo "  INSTALLED: $p"; found=1; }
    done
    [ "$found" = 0 ] && echo "  not installed (no launcher in Startup folder)."
    exit 0 ;;

  uninstall)
    removed=0
    for p in "$VBS_PATH" "$CMD_PATH"; do
      [ -f "$p" ] && { rm -f "$p" && echo "removed: $p" && removed=1; }
    done
    [ "$removed" = 0 ] && echo "nothing to remove (no launcher found)."
    echo "Note: this does not stop already-running containers."
    exit 0 ;;

  install)
    [ -f "$AUTOSTART_SCRIPT" ] || die "host-autostart.sh not found at $AUTOSTART_SCRIPT"
    [ -x "$AUTOSTART_SCRIPT" ] || chmod +x "$AUTOSTART_SCRIPT" 2>/dev/null || true
    mkdir -p "$LOG_DIR" || die "could not create log dir $LOG_DIR"
    mkdir -p "$STARTUP_DIR" || die "could not access Startup folder: $STARTUP_DIR"

    # If switching launcher type, drop the other one so only one fires.
    if [ "$USE_CMD" = 1 ]; then
      rm -f "$VBS_PATH"
      cmd_body > "$CMD_PATH" || die "could not write $CMD_PATH"
      TARGET="$CMD_PATH"
    else
      rm -f "$CMD_PATH"
      vbs_body > "$VBS_PATH" || die "could not write $VBS_PATH"
      TARGET="$VBS_PATH"
    fi

    echo "Installed logon auto-start:"; show_resolved
    echo
    echo "Launcher written to:"
    echo "  $TARGET"
    echo
    echo "It will run at your next Windows logon. To test it now without rebooting:"
    echo "  $AUTOSTART_SCRIPT"
    echo "Check the log any time with:  cat '$LOG_FILE'"
    echo "Remove it with:              scripts/install-autostart.sh --uninstall"
    exit 0 ;;
esac
